########################################################################
#  Make файл для эльбруса
########################################################################
 
units     = raid crc igzip erasure_code
#units     = raid

default: lib

include $(foreach unit,$(units), $(unit)/Makefile.elb)

# Override individual lib names to make one inclusive library.
lib_name := bin/isa-l.a

include make.elb

VPATH = . $(units) include
